### ISSUE TITLE
Validate boot time is recent

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/glaukos#26]
https://github.com/xmidt-org/glaukos/blob/54186c656fefed78533481ef2c064e75c6fcbaca/event/parsing/bootTimeParser.go#L81

Make sure the boot time for the online event is within like a month/week/something.  There are boxes out there sending non-zero, invalid boot times (such as numbers < 50).

**Comment by kristinaspring** [comment]
Alternatively, we can calculate the time difference with the online event's birthdate instead of its boot time.

**Comment by schmidtw** [comment]
Ideally it would be good to make a configurable window that boot time values before are ignored and a metric `invalid boot time` is incremented (per CPE hardware, firmware, etc).

The configurable window being a duration seems reasonable.

**Comment by kristinaspring** [comment]
This validation will not be needed with the change to not use the boot time in our calculations, per Jasmine's PR.
